apiVersion: v2
name: elpio
description: Turn any Kubernetes cluster into a private serverless platform.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/altikva/elpio
sources:
  - https://github.com/altikva/elpio
keywords:
  - serverless
  - knative
  - keda
  - operator
maintainers:
  - name: Joy Ndjama
    email: joy.ndjama@altikva.com
